[launcher]
version = 0.0.0+8dae258
description = The CriblSearch app for Splunk allows users to run searches against a configured Cribl search environment and return the results in Splunk Search
author = Discovered Intelligence Inc.

[id]
version = 0.0.0+8dae258
name = criblsearch

[install]
build = 1777384701
is_configured = false
state = enabled

[package]
id = criblsearch
check_for_updates = true

[ui]
label = CriblSearch App for Splunk
supported_themes = light, dark
is_visible = true

[triggers]
reload.criblsearch_settings = simple
reload.criblsearch_account = simple
