[source::...criblsearch.log]
sourcetype = criblsearch:cmd:log

[criblsearch:cmd:log]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2},
TIME_PREFIX = ^
MAX_TIMESTAMP_LOOKAHEAD = 30
TIME_FORMAT = %Y-%m-%d %H:%M:%S,%3Q%z
TRUNCATE = 99999

EXTRACT-log_level = ^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2},\d{3}\+\d{4}\s(?<log_level>\w+)
EXTRACT-cribl_job_params = cribl_instance:\s(?<cribl_instance>[^,]+),\sgroup:\s(?<group>.+)_search,\sjob-id:\s(?<cribl_job_id>.+)
EXTRACT-splunk_job_params = sid:\s(?<sid>[0-9\.]+),\susername:\s(?<username>\w+),\ssearch_arguments:\s\[(?<args>[^\]]+)\],\searliest:\s(?<earliest>[0-9\.]+),\slatest:\s(?<latest>[0-9\.]+)
EXTRACT-job_status = Job\sStatus:\s(?<job_status>\w+)
EXTRACT-invocation_id = invocation_id=(?<invocation_id>[0-9:\.]+)
EXTRACT-events_returned = Dispatching\s(?<events_returned>\d+)\sevents

FIELDALIAS-invocation_time = invocation_id AS invocation_time