[admin:criblsearch_configuration]
match = /
members = criblsearch_account, criblsearch_settings

[admin_external:criblsearch_account]
handlertype = python
python.version = python3
handlerfile = criblsearch_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:criblsearch_settings]
handlertype = python
python.version = python3
handlerfile = criblsearch_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true
