[expose:criblsearch_account]
pattern = criblsearch_account
methods = POST, GET

[expose:criblsearch_account_specified]
pattern = criblsearch_account/*
methods = POST, GET, DELETE

[expose:criblsearch_settings]
pattern = criblsearch_settings
methods = POST, GET

[expose:criblsearch_settings_specified]
pattern = criblsearch_settings/*
methods = POST, GET, DELETE
